#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8080" \
        s6-setuidgid abc \
            /app/pwndrop/pwndrop \
                -debug \
                -no-autocert \
                -no-dns \
                -config /defaults/pwndrop.ini
