#!/usr/bin/with-contenv bash

mkdir -p /config/data

if [ ! -f "/config/data/pwndrop.db" ]; then
  SECRET_PATH=${SECRET_PATH:-/pwndrop}
  echo "new install detected, starting pwndrop with secret path ${SECRET_PATH}"
  echo -e "\n[setup]\nsecret_path = \"${SECRET_PATH}\"" >> /defaults/pwndrop.ini
else
  echo "existing install detected"
fi

# permissions
chown -R abc:abc \
  /config \
  /defaults \
  /app
